<?php
// $Id$

/**
 * Implementation of hook_enable().
 */
function himinglaeva_enable() {
  // Need to flush autoload cache
  autoload_flush_caches();
}

/**
 * Implementation of hook_autoload_info().
 */
function himinglaeva_autoload_info() {
  return array(
    'PlatformsResource' => array(
      'file'  => 'resources/platforms.php',
    ),
  );
}

/**
 * Implementation of hook_services_resources().
 */
function himinglaeva_services_resources() {
  return array(
    'platform' => ServicesOop::definitionFromClass('PlatformsResource'),
  );
}

/**
 * Simple helper function for returning a status response to the client
 *
 * @param   bool      $status
 *  TRUE for success, FALSE for error
 * @param   string    $message
 * @return  array
 */
function himinglaeva_status($status, $message = FALSE) {
  $response = array();
  $response['status'] = $status ? 'success' : 'error';
  if (is_string($message)) {
    $response['msg'] = $message;
  }
  return $response;
}